### ISSUE TITLE
dark-mode theming (with redux)

### ISSUE THREAD

**Issue by joshidipesh12** [joshidipesh12/rss-swift#11] opened 2022-10-16 14:28 UTC

**Comment by joshidipesh12** [comment] 2022-10-17 15:19
@darshita10308 👍
@apassan23 I'm merging these, plz have a look if we require additional apparatus for theming or something needs fixing.

**Comment by joshidipesh12** [comment] 2022-10-17 15:43
# Getting Error on theme change
![image](https://user-images.githubusercontent.com/66198105/196222117-ed2109e2-de77-4512-8094-b135d508a14f.png)

### TypeError: Cannot read properties of undefined (reading 'matches')
hooks\useThemeDetector.js (6:21) @ MediaQueryList.mqListener

**Comment by darshita10308** [comment] 2022-10-19 08:31
@apassan23 plz try the new theming mechanism on pages/feeds/index.js

**Comment by apassan23** [comment] 2022-10-19 13:48
Yes, its working as intended @darshita10308. You can close this issue now if there's nothing else.

**Closed** 2022-10-19 14:13 UTC
